import type { ToDoTaskDto } from "./types";

export const testTasks: ToDoTaskDto[] = [
    {
        id: 10,
        name: 'A - Task 10',
        createdUTC: new Date('2026-06-10'),
        completedUTC: null,
        deadlineUTC: new Date('2026-05-10'),
        description: "This is a test description",
    },
    {
        id: 9,
        name: 'A - Task 9',
        createdUTC: new Date('2026-06-9'),
        completedUTC: null,
        deadlineUTC: null,
        description: "This is a test description",
    },
    {
        id: 8,
        name: 'A - Task 8',
        createdUTC: new Date('2026-06-8'),
        completedUTC: null,
        deadlineUTC: null,
        description: "This is a test description",
    },
    {
        id: 7,
        name: 'A - Task 7',
        createdUTC: new Date('2026-06-7'),
        completedUTC: null,
        deadlineUTC: null,
        description: "This is a test description",
    },
    {
        id: 6,
        name: 'A - Task 6',
        createdUTC: new Date('2026-06-6'),
        completedUTC: null,
        deadlineUTC: null,
        description: "This is a test description",
    },
    {
        id: 5,
        name: 'A - Task 5',
        createdUTC: new Date('2026-06-5'),
        completedUTC: null,
        deadlineUTC: null,
        description: "This is a test description",
    },
    {
        id: 4,
        name: 'A - Task 4',
        createdUTC: new Date('2026-06-4'),
        completedUTC: null,
        deadlineUTC: null,
        description: "This is a test description",
    },
    {
        id: 3,
        name: 'A - Task 3',
        createdUTC: new Date('2026-06-3'),
        completedUTC: null,
        deadlineUTC: null,
        description: "This is a test description",
    },
    {
        id: 2,
        name: 'A - Task 2',
        createdUTC: new Date('2026-06-2'),
        completedUTC: null,
        deadlineUTC: new Date('2026-06-20T19:38:16.207'),
        description: null,
    },
    {
        id: 1,
        name: 'A - Task 1',
        createdUTC: new Date('2026-06-1'),
        completedUTC: new Date('2026-06-07T19:38:13.215'),
        deadlineUTC: null,
        description: null,
    },
];
